services:
  - type: web
    name: toadle-website
    env: static
    branch: main
    buildCommand: npm ci && rm -rf .astro && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 22
